name: project_mesa
description: A simple app to check item value on warframe market powered by OCR.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  app_rename: ^0.0.1
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.8
  flutter_typeahead: ^4.0.0
  google_mlkit_text_recognition: ^0.4.0
  http: ^0.13.5
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#101619"
  image: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/jsons/items.json
    - assets/images/
    - assets/icons/
